-- IMPORTANT: important the icons module should be loaded before the ui module
require("plugins.icons")
require("plugins.ui")
require("plugins.parsers")
require("plugins.terminal")
require("plugins.comments")
require("plugins.git")
require("plugins.chatgpt")
require("plugins.dap")
require("plugins.clipboard")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.marking")
require("plugins.navigation")

